[package]
name = "intercomm"
version = "0.0.0"
edition = "2021"

[dependencies]
io-extras = "0.17.0"
ordered-float = "3.0.0"

[dev-dependencies]
io-lifetimes = "1.0.0"

[target.'cfg(not(windows))'.dependencies]
rustix = { version = "0.37.0" }
